packages:
  - "."
  - "generated"

# TODO: enable this when we are out of alpha
# scan: pnpx snyk test envio@3.0.0-alpha.11
#minimumReleaseAge: 10080 # 1 week
minimumReleaseAge: 1440 # 1 day
onlyBuiltDependencies:
  - "@biomejs/biome"
  - lefthook
