packages:
  - "."

minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude: []

allowBuilds:
  "@biomejs/biome": true
  lefthook: true
  esbuild: false

trustPolicy: no-downgrade
trustPolicyExclude: []
